version: '3.7'
services:
  dev:
    image: kainonly/composer-alpine
    command: 'composer update --prefer-dist -o --ignore-platform-reqs'
    volumes:
      - ../.composer:/tmp
      - ./:/app
  update:
    image: kainonly/composer-alpine
    command: 'composer update --prefer-dist -o --no-dev --ignore-platform-reqs'
    volumes:
      - ../.composer:/tmp
      - ./:/app